In [22]:
import numpy as np

arr1 = np.random.randint(0, 100, 10_000)
arr1

array([26, 40, 28, ..., 31, 51, 97])

In [23]:
print('Primeiro elemento', arr1[0])
print('12 elemento', arr1[11])

Primeiro elemento 26
12 elemento 45


In [24]:
# Conseguimos fatiar o array (slice) semelhante a listas
print('Pegando os quatro primeiros elementos', arr1[: 4], 'tamanho', len(arr1[: 4]))
print('Pegando os elementos internos', arr1[900: 8500], 'tamanho', len(arr1[900: 8500]))

Pegando os quatro primeiros elementos [26 40 28 55] tamanho 4
Pegando os elementos internos [60 18 83 ... 51 31 67] tamanho 7600


In [25]:
mat = np.random.randint(0, 100, (3, 4))
mat

array([[22, 24, 65, 43],
       [22, 75, 41, 73],
       [ 8, 41, 10,  6]])

In [26]:
print('Shape', mat.shape)

Shape (3, 4)


In [27]:
lista = list(mat)
col = []
for linha in lista:
  col.append(linha[0])

print(col)

[22, 22, 8]


In [28]:
# Pegando a primeira linha
print(mat[0])
print('-'*32)
# As duas últimas linhas
print(mat[1:])
print(mat[-2:])
print('-'*32)
# A primeira coluna
print(mat[ : , 0]) # O `:`significa todas as linhas, o zeo representa a coluna
print('-'*32)

# As três últimas colunas e duas últimas linhas
print(mat[-2: , -3: ])
print('-'*32)

# Podemos filtrar usando os indices
# Pegando a primeira e terceira linha e todas as colunas
print(mat[[0,2], :])
print('-'*32)
# Pegando a segunda e quarta coluna
print(mat[ : , [1, 3]])

[22 24 65 43]
--------------------------------
[[22 75 41 73]
 [ 8 41 10  6]]
[[22 75 41 73]
 [ 8 41 10  6]]
--------------------------------
[22 22  8]
--------------------------------
[[75 41 73]
 [41 10  6]]
--------------------------------
[[22 24 65 43]
 [ 8 41 10  6]]
--------------------------------
[[24 43]
 [75 73]
 [41  6]]
