**Drops**

Crie uma matriz 10x8.

Pegue apenas as linhas cujo indices são pares (0, 2, etc) e cuja colunas sejam impares (1, 3, etc).

Dica: Utilize primeiro o slice por linhas e depois por coluna!

Não faça algo do tipoe `mat[[0,2], [1,3]]`, prefira

```
res = mat[[0,2], :]
mat_final = res[:, [0,2]]
```

In [2]:
import numpy as np


# Linha para permitir a reprodutibilidade do exercício
np.random.seed(0)
n_linhas = 10
n_cols = 8
mat = np.random.randint(0, 10, (n_linhas, n_cols))
print('Shape', mat.shape)
print('-'*32)
print(mat)
print('-'*32)
col_impar = list(filter(lambda x: x%2 != 0, range(n_cols)))
linha_par = list(filter(lambda x: x%2 == 0, range(n_linhas)))
print('col_impar', col_impar)
print('linha_par', linha_par)
print('-'*32)

# Quando queremos filtrar por duas listas
# Devemos fazer de forma sequencial
filtrando_linhas = mat[linha_par, :]
filtrando_colunas = filtrando_linhas[:, col_impar] 

Shape (10, 8)
--------------------------------
[[5 0 3 3 7 9 3 5]
 [2 4 7 6 8 8 1 6]
 [7 7 8 1 5 9 8 9]
 [4 3 0 3 5 0 2 3]
 [8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7]
 [2 0 0 4 5 5 6 8]
 [4 1 4 9 8 1 1 7]
 [9 9 3 6 7 2 0 3]
 [5 9 4 4 6 4 4 3]]
--------------------------------
col_impar [1, 3, 5, 7]
linha_par [0, 2, 4, 6, 8]
--------------------------------
