In [33]:
import numpy as np
import random
from random import randint 

arr = np.random.randint(0, 100, (3, 5))
print(arr)
print('-'*100)

# Somando uma constante
print(arr + 892)
print('-'*100)
# Subtraindo uma constante
print(arr - 1000)
print('-'*100)
# Divisão com uma constante
print(arr / 100)
print('-'*100)
# Divisões por zero gera infinito
# print(arr / 0)

# Log (utilizando np.log)
print(np.log(arr + 0.0000001)) # Adicionando um valor muito muito pequeno para evitar log de zero (0)
print('-'*100)
# Exponencial
print(np.square(arr))
print(arr**2)
print('-'*100)

# Raiz quadrada
print(arr)
print(np.sqrt(arr))
print('-'*100)

[[83 10 10 40 12]
 [ 9 92 39 84 70]
 [21 36 42 61 39]]
----------------------------------------------------------------------------------------------------
[[975 902 902 932 904]
 [901 984 931 976 962]
 [913 928 934 953 931]]
----------------------------------------------------------------------------------------------------
[[-917 -990 -990 -960 -988]
 [-991 -908 -961 -916 -930]
 [-979 -964 -958 -939 -961]]
----------------------------------------------------------------------------------------------------
[[0.83 0.1  0.1  0.4  0.12]
 [0.09 0.92 0.39 0.84 0.7 ]
 [0.21 0.36 0.42 0.61 0.39]]
----------------------------------------------------------------------------------------------------
[[4.41884061 2.3025851  2.3025851  3.68887946 2.48490666]
 [2.19722459 4.52178858 3.66356165 4.4308168  4.24849524]
 [3.04452244 3.58351894 3.73766962 4.11087387 3.66356165]]
----------------------------------------------------------------------------------------------------
[[6889  100  100 1600  14

In [34]:
mat  = np.random.randint(0, 100, (3, 5))


print("Max valor:", mat.max())
# Valor máximo por coluna
print("Max coluna:", mat.max(axis=0))
# Valor máximo por linha
print("Max linha:", mat.max(axis=1))
print('-'*100)

Max valor: 88
Max coluna: [88 58 75 78 67]
Max linha: [80 88 88]
----------------------------------------------------------------------------------------------------


In [35]:
# Indice cujo valor é o minimo (`argmin`)
# -> Volta o index na matriz considerando que ela é unidimensional
print("Min valor:", mat.argmin())
# Para pegar o valor, precisamos achatar a matriz e para tal utilizamos o reshape
print(mat.reshape(-1, 1)[0])

# Indice cujo valor é o minimo por coluna
print('Min col:', mat.argmin(axis=0))

# Indice cujo valor é o minimo por linha
print('Min linha:', mat.argmin(axis=1))

Min valor: 4
[80]
Min col: [0 0 0 1 0]
Min linha: [4 3 4]


In [36]:
# Soma total
print('Valor total:', mat.sum())
# Soma por coluna
print('Valor coluna:', mat.sum(axis=0))
# Soma por linha
print('Valor linha:', mat.sum(axis=1))

Valor total: 783
Valor coluna: [256 155 146 144  82]
Valor linha: [201 306 276]


In [37]:
# Média total
print('Média valor:', mat.mean())

# Média por coluna
print('Média coluna:', mat.mean(axis=0))

# Média por linha
print('Média linha:', mat.mean(axis=1))

Média valor: 52.2
Média coluna: [85.33333333 51.66666667 48.66666667 48.         27.33333333]
Média linha: [40.2 61.2 55.2]


In [38]:
# Desvio padrão total
print('Desvio padrão:', mat.std())

# Desvio padrão coluna
print('Desvio padrão por coluna:', mat.std(axis=0))

# Desvio padrão linha
print('Desvio padrão por linha:', mat.std(axis=1))

Desvio padrão: 26.803482360817718
Desvio padrão por coluna: [ 3.77123617  6.3420992  19.60158724 24.49489743 28.40578971]
Desvio padrão por linha: [25.53742352 23.74363072 26.55861442]
