In [7]:

import numpy as np

# O where funciona para cada elemento da lista (array)!
# Com Python puro seria como compreensão de lista
mat = np.random.randint(0, 100, (3, 3))
print('mat')
print(mat)
print('-'*21)
np.where(mat%2 == 0, mat**2, -100)

mat
[[70 79 87]
 [16 70 78]
 [42 35 22]]
---------------------


array([[4900, -100, -100],
       [ 256, 4900, 6084],
       [1764, -100,  484]], dtype=int32)

In [8]:
%%time
arr = np.arange(0, 10_000)
_ = [x**2 if x%2 == 0 else -100 for x in arr]

CPU times: total: 0 ns
Wall time: 0 ns


In [9]:
%%time
arr = np.arange(0, 10_000)
_ = np.where(arr%2==0, arr**2, -100)

CPU times: total: 0 ns
Wall time: 0 ns


In [10]:
# Podemos encadear funções where
# Muito parecido com o excel IF(cond2, IF(cond, TRUE, FALSE), FALSE)
arr = np.random.randint(0, 100, 1_000)
filtro_lista = [0, 20, 30]
np.where((arr%2==0),
         np.where(arr > 50, # Verificando se o número par é maior que 50
                  -1000,    # Se for maior que 50 e par, coloque -1000
                  -10       # Se for par e menor ou igual a 50 coloque -10
                ),
         arr # Se impar volta o número
  )

array([  -10,    39,   -10,    47,   -10,    67,    75, -1000,    39,
          17,    97,    11,   -10, -1000,   -10, -1000,    65,   -10,
          51,    29,     1,   -10,   -10,    27,    53,    77,    35,
          73,    57, -1000, -1000,    13,     3,   -10,   -10,   -10,
          39, -1000,    25,    37, -1000, -1000,   -10,    43, -1000,
          39, -1000,    65,    79, -1000,    83,     5,   -10,   -10,
         -10,    81,   -10,    19, -1000,    41,   -10,    71,    61,
         -10,     5,    75, -1000,    91,    25,    31, -1000,   -10,
         -10,   -10,   -10,    39,    17,    41,    47, -1000, -1000,
         -10,   -10,   -10,    61,    79,    31,    17, -1000, -1000,
          41,    95,    23,   -10,   -10,    23, -1000,    21, -1000,
          15, -1000,    27,    19,    35, -1000,    87,    43,    65,
         -10,    39,   -10,    63, -1000,   -10,   -10,    59,   -10,
          99,    81,    37, -1000, -1000,     1,    87,    49, -1000,
          19,   -10,