10 - Crie outro array aleatório, porém, dessa vez, com 25 elementos inteiros, no intervalo [50, 100). Em seguida, converta esse array em uma matriz 5 x 5.

In [13]:
import math
import numpy as np
from random import randint


mtx = np.array([np.arange(6), np.arange(10, 16), np.arange(20, 26), np.arange(30, 36), np.arange(40, 46), np.arange(50, 56)])

vermelho = mtx[0,3:5]
print('\033[31m {}\033[m'.format(vermelho))
print('-'*100,'\n')

azul = mtx[:,2]
print('\033[36m {}\033[m'.format(azul))
print('-'*100,'\n')

roxo = mtx[2::2,::2]
print('\033[35m {}\033[m'.format(roxo))
print('-'*100,'\n')

verde = mtx[4:,4:]

print('\033[32m {}\033[m'.format(verde ))
print('-'*100,'\n')

 [3 4]
---------------------------------------------------------------------------------------------------- 

 [ 2 12 22 32 42 52]
---------------------------------------------------------------------------------------------------- 

 [[20 22 24]
 [40 42 44]]
---------------------------------------------------------------------------------------------------- 

 [[44 45]
 [54 55]]
---------------------------------------------------------------------------------------------------- 



In [14]:
np.random.seed(0)
n_linhas = 5
n_cols = 5
matrix_5x5  = np.random.randint(50, 100, (n_linhas, n_cols))
print('\033[34m {}\033[m'.format(matrix_5x5))
print('-'*100,'\n')

# OUTRA FORMA
matriz = np.linspace(50, 100, 25).reshape(5, 5)
print(matriz)
print('-'*100,'\n')
# OUTRA FORMA

matri_z = np.random.randint(50, 100, 25).reshape(5, 5)
print(matri_z)

 [[94 97 50 53 53]
 [89 59 69 71 86]
 [73 56 74 74 62]
 [51 88 89 73 96]
 [74 67 87 75 63]]
---------------------------------------------------------------------------------------------------- 

[[ 50.          52.08333333  54.16666667  56.25        58.33333333]
 [ 60.41666667  62.5         64.58333333  66.66666667  68.75      ]
 [ 70.83333333  72.91666667  75.          77.08333333  79.16666667]
 [ 81.25        83.33333333  85.41666667  87.5         89.58333333]
 [ 91.66666667  93.75        95.83333333  97.91666667 100.        ]]
---------------------------------------------------------------------------------------------------- 

[[58 59 70 66 55]
 [65 97 50 68 85]
 [74 99 79 69 69]
 [64 89 82 51 59]
 [82 81 60 73 85]]
